name = "classes"

[generalClassInfo]
name = "School of Magical Strings"
term = "Fall Term 2023"
time = "Tuesdays, 6-7pm PST"
start = "October 24"
end = "December 5"
where = "Virtually on Zoom"
fee = "$195"
description =[
  "The Healing Mystery of Music",
  "Many harp players know the potential for healing with music. How does one go about it? Although there are several great certified programs for learning specific skills in this regard, it doesn’t require training to know the benefits we give even in the simple act of playing a few arpeggios in a room with people; it warms the atmosphere, and they respond positively. In a world that is suffering from catastrophes of climate change, war, political divides, personal loss, and all manner of diseases, we are uniquely positioned to do something good with our harps, however small it may seem. Even science has acknowledged the importance of music in many aspects of human development and healing. The harp, as an archetypal instrument going back to ancient times in human history, is uniquely positioned to be an instrument for healing. In this class we’re going to work with a few established pieces that grew out of improvisations. Simple tools will be given to help you improvise. This is important, as the work of healing sometimes calls on us to be spontaneously creative. It may sound daunting, but it doesn’t have to be difficult. The levels of playing for these pieces ranges from very simple to complex. Beginners*, do not fret! There is material here for you. Also, know that the classes are all recorded for the benefit of future reference for every student.",
  "A Note to Beginners: There is much in this content that you will be able to learn; and other parts that will seem more advanced. In preparation for this class, I highly recommend that you review my beginner’s instructional harp video, ‘Magic of the Celtic Harp’. All those who register will be sent this link.",
  "The class fee for the six-week term is $195.",
  "Contact us to register!"
]

